/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/R5WTiMBE8vx
 */
import Link from "next/link"
import { JSX, SVGProps } from "react"

export function Feed() {
  return (
    <div className="bg-white dark:bg-gray-950">
      <div className="py-6 md:py-12 lg:py-16">
        <div className="mx-auto grid max-w-6xl gap-6 px-4 md:gap-8 md:px-6 lg:gap-12">
          <div className="space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tight">The Joke Tax: Why Taxing Laughter Was No Joke</h2>
              <p className="text-gray-500 dark:text-gray-400">
                Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
              </p>
            </div>
            <Link className="flex items-center font-semibold underline" href="#">
              Read more
              <span className="ml-1.5">
                <ChevronRightIcon className="w-4 h-4" />
              </span>
            </Link>
          </div>
          <hr className="border-gray-200 dark:border-gray-800" />
          <div className="space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tight">The Joke Tax: Why Taxing Laughter Was No Joke</h2>
              <p className="text-gray-500 dark:text-gray-400">
                Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
              </p>
            </div>
            <Link className="flex items-center font-semibold underline" href="#">
              Read more
              <span className="ml-1.5">
                <ChevronRightIcon className="w-4 h-4" />
              </span>
            </Link>
          </div>
          <hr className="border-gray-200 dark:border-gray-800" />
          <div className="space-y-4">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tight">The Joke Tax: Why Taxing Laughter Was No Joke</h2>
              <p className="text-gray-500 dark:text-gray-400">
                Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
              </p>
            </div>
            <Link className="flex items-center font-semibold underline" href="#">
              Read more
              <span className="ml-1.5">
                <ChevronRightIcon className="w-4 h-4" />
              </span>
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}


function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
