/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UdwjlzUIuh2
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardContent, Card } from "@/components/ui/card"

export type UserType = {
  id: string
  username: string
  name: string
  email: string
  bio: string
  role: string
  avatarSrc?: string
  initials: string
}

export function ProfileCard({ user }: { user: UserType }) {
  return (
    <Card className="w-full max-w-sm">
      <div className="flex flex-col items-center gap-2 p-6">
        <div className="text-lg font-bold">{user.name}</div>
      </div>
      <CardContent className="p-6 border-t border-gray-100 dark:border-gray-800">
        <dl className="grid gap-2 text-sm">
          <div className="font-medium">Bio</div>
          <div className="text-sm text-gray-500 dark:text-gray-400">{user.bio}</div>
          <div className="font-medium">Email</div>
          <div>{user.email}</div>
        </dl>
      </CardContent>
    </Card>
  )
}
