/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DM6G4kKr194
 */
import { CardTitle, CardDescription, CardHeader, CardFooter, Card } from "@/components/ui/card"
import { Avatar } from "@/components/ui/avatar"

export function StoryCard() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>The Haunted House</CardTitle>
        <CardDescription>A spooky tale about a house on the hill.</CardDescription>
      </CardHeader>
      <CardFooter>
        <div className="flex items-center space-x-2">
          <Avatar className="w-6 h-6">
            <div>AC</div>
          </Avatar>
          <div className="text-sm font-medium">Author: Alice Clark</div>
        </div>
      </CardFooter>
    </Card>
  )
}
