/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/T68n9V0xvm5
 */
import { NavigationMenuLink, NavigationMenuItem, NavigationMenuList, NavigationMenu } from "@/components/ui/navigation-menu"
import { Button } from "@/components/ui/button"
import { Avatar } from "@/components/ui/avatar"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"

export function UIkit() {
  return (
    <div className="border-b">
      <div className="container px-4">
        <div className="flex items-center justify-between h-14">
          <div className="flex items-center gap-4">
            <div className="text-lg font-semibold">Company</div>
            <div className="hidden md:flex">
              <NavigationMenu>
                <NavigationMenuList>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="font-medium group inline-flex items-center gap-2 px-2 rounded-md text-sm transition-colors hover:underline hover:text-gray-900 dark:hover:text-gray-50"
                      href="#"
                    >
                      Home
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="font-medium group inline-flex items-center gap-2 px-2 rounded-md text-sm transition-colors hover:underline hover:text-gray-900 dark:hover:text-gray-50"
                      href="#"
                    >
                      Features
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink
                      className="font-medium group inline-flex items-center gap-2 px-2 rounded-md text-sm transition-colors hover:underline hover:text-gray-900 dark:hover:text-gray-50"
                      href="#"
                    >
                      Pricing
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                </NavigationMenuList>
              </NavigationMenu>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="hidden md:flex items-center gap-2">
              <Button size="sm" variant="outline">
                New Project
              </Button>
            </div>
            <div className="flex items-center gap-4">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button className="h-8 w-8 rounded-full" size="sm" variant="ghost">
                    <Avatar className="w-6 h-6" />
                    <div>Toggle</div>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-56">
                  <DropdownMenuLabel>My Account</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>Profile</DropdownMenuItem>
                  <DropdownMenuItem>Billing</DropdownMenuItem>
                  <DropdownMenuItem>Team</DropdownMenuItem>
                  <DropdownMenuItem>Subscription</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
